services:
  postgres:
    container_name: 'coach-wise-pg'
    image: 'postgres:14.4-alpine'
    environment:
      POSTGRES_USER: 'coachwise'
      POSTGRES_PASSWORD: 'passwd'
      POSTGRES_DB: 'coachwise'
      PGDATA: '/data/postgres'
    volumes:
      - '../coachwise-postgres:/data/postgres'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: 'always'

  nats:
    container_name: 'coach-wise-nats'
    image: 'nats:2.10-alpine'
    command: '-js -m 8222'
    expose:
      - '4222'
    ports:
      - '4222:4222'   # client connections
      - '8222:8222'   # monitoring
    restart: 'always'

networks:
  default:
    driver: bridge
